apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ${NAMESPACE}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: cloudserver
  namespace: ${NAMESPACE}
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: cloudserver
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: ${NAMESPACE}
  labels:
    app: kafka-broker
spec:
  ports:
    - name: backend
      port: 9092
      targetPort: 9092
  selector:
    app: kafka-broker
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: ${NAMESPACE}
  labels:
    app: zookeeper
spec:
  ports:
    - name: backend
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
---
