apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
  namespace: ${NAMESPACE}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata-claim
  namespace: ${NAMESPACE}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage
