apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine3.20
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          volumeMounts:
            - name: nginx-settings
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-tls-certificate
              mountPath: /etc/tls/certs/fullchain.pem
              subPath: fullchain.pem
            - name: nginx-tls-certificate-key
              mountPath: /etc/tls/private/privkey.pem
              subPath: privkey.pem
      volumes:
        - name: nginx-settings
          configMap:
            name: nginx-settings
        - name: nginx-tls-certificate
          configMap:
            name: nginx-tls-certificate
        - name: nginx-tls-certificate-key
          configMap:
            name: nginx-tls-certificate-key
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: ${NAMESPACE}
spec:
  serviceName: minio
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-10-13T13-34-11Z
          imagePullPolicy: Always
          args:
            - server
            - http://minio-{0...3}.minio.${NAMESPACE}.svc.cluster.local/data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_BROWSER_REDIRECT
              value: "false"
            - name: MINIO_ACCESS_KEY
              value: "${ACCESS_KEY}"
            - name: MINIO_SECRET_KEY
              value: "${SECRET_KEY}"
          ports:
            - name: api
              containerPort: 9000
            - name: frontend
              containerPort: 9001
          volumeMounts:
            - name: data-volume
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: ${STORAGE_DATA_SIZE}G
        storageClassName: linode-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  namespace: ${NAMESPACE}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
        - name: nodered
          image: nodered/node-red:latest
          imagePullPolicy: Always
          ports:
            - name: frontend
              containerPort: 1880
